### ISSUE TITLE
top-level script runs on konohac

### ISSUE THREAD

**Issue by shidasan** [imasahiro/konohascript#8]
top-level script runs on konohac

hello.k

using konoha.compiler.*;
OUT.println("hello world");

$konohac hello.k > hello.kc

hello.kc

hello world
def null Script. ( konoha.compiler.Script script0_0 ) {
BasicBlock0
ous6_0 = call konoha.OutputStream System.getOut ( ) @static
str7_0 = const konoha.String "hello world"
_ = call null OutputStream.println ( ous6_0 str7_0 ) @nonstatic
_ = return
}

**Comment by imasahiro** [comment]
fix @ 7cc7ed3
